networks:
  my-network:
    driver: bridge

services:
  gateway-service:
    image: gateway:0.2.0
    container_name: gateway-service
    build:
      context: /gatewayAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    networks:
      - my-network

  product-service:
    image: product-service:0.2.0
    container_name: product-service
    build:
      context: /product-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - product-database
      - product-cache
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-database/product_db
    networks:
      - my-network

  product-database:
    image: postgres:bullseye
    container_name: product-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    volumes:
      - product_db-data:/var/product_postgresql/data
    restart: always
    networks:
      - my-network

  product-cache:
    image: redis:8
    container_name: product-cache
    ports:
      - "6379:6379"
    restart: always
    networks:
      - my-network

  order-service:
    image: order-service:0.1.0
    container_name: order-service
    build:
      context: /order-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - order-database
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-database/order_db
    networks:
      - my-network

  order-database:
    image: postgres:bullseye
    container_name: order-database
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    volumes:
      - order_db-data:/var/order_postgresql/data
    restart: always
    networks:
      - my-network

  user-service:
    image: user_service:0.0.4
    container_name: user-service
    build:
      context: /user-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - user-database
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-database/user_db
    networks:
      - my-network

  user-database:
    image: postgres:bullseye
    container_name: user-database
    ports:
      - "5434:5434"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    volumes:
      - user_db-data:/var/order_postgresql/data
    restart: always
    networks:
      - my-network

volumes:
  product_db-data:
  order_db-data:
  user_db-data: