server:
  port: 8080

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: DEBUG
        web: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        ssl:
          useInsecureTrustManager: true
      default-filters:
        - StripPrefix=1
        - name: LoggingFilter
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20